import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

/**
 * Credential data for PDF generation
 */
export interface CredentialPDFData {
  fullName: string;
  email: string;
  password: string;
  role: string;
  schoolName?: string;
  generatedAt: Date;
  generatedBy?: string;
}

/**
 * Generate PDF buffer for credentials
 */
export function generateCredentialPDF(data: CredentialPDFData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 }
    });

    const buffers: Buffer[] = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfBuffer = Buffer.concat(buffers);
      resolve(pdfBuffer);
    });
    doc.on('error', reject);

    // Header
    doc
      .fontSize(24)
      .fillColor('#667eea')
      .text('Account Credentials', { align: 'center' })
      .moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor('#666')
      .text('School Management System', { align: 'center' })
      .moveDown(2);

    // Credential box
    doc
      .rect(50, doc.y, 500, 200)
      .strokeColor('#667eea')
      .lineWidth(2)
      .stroke();

    doc
      .fontSize(14)
      .fillColor('#333')
      .text('Account Information', 70, doc.y + 20)
      .moveDown(1);

    doc
      .fontSize(12)
      .fillColor('#333')
      .text(`Full Name: ${data.fullName}`, { indent: 20 })
      .moveDown(0.5)
      .text(`Email: ${data.email}`, { indent: 20 })
      .moveDown(0.5)
      .text(`Role: ${data.role}`, { indent: 20 })
      .moveDown(0.5);

    if (data.schoolName) {
      doc.text(`School: ${data.schoolName}`, { indent: 20 }).moveDown(0.5);
    }

    doc.moveDown(1);

    doc
      .fontSize(14)
      .fillColor('#333')
      .text('Login Credentials', { indent: 20 })
      .moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor('#333')
      .text(`Email: ${data.email}`, { indent: 40 })
      .moveDown(0.5)
      .text(`Temporary Password: ${data.password}`, { indent: 40 })
      .moveDown(1);

    // Security warning
    doc
      .fontSize(10)
      .fillColor('#dc3545')
      .text('⚠️ IMPORTANT: Please change your password after first login for security.', {
        indent: 20,
        align: 'left'
      })
      .moveDown(2);

    // Footer
    const footerY = doc.page.height - 100;
    doc
      .fontSize(10)
      .fillColor('#999')
      .text(
        `Generated on: ${data.generatedAt.toLocaleString()}`,
        50,
        footerY,
        { align: 'left' }
      );

    if (data.generatedBy) {
      doc.text(`Generated by: ${data.generatedBy}`, 50, footerY + 15, { align: 'left' });
    }

    doc.text(
      'Keep this document secure. Do not share your credentials with anyone.',
      50,
      footerY + 30,
      { align: 'left', width: 500 }
    );

    doc.end();
  });
}

/**
 * Generate PDF as base64 string (for frontend download)
 */
export async function generateCredentialPDFBase64(data: CredentialPDFData): Promise<string> {
  const buffer = await generateCredentialPDF(data);
  return buffer.toString('base64');
}

