"use strict";
/**
 * Shared Types
 *
 * Types and interfaces shared between backend and frontend
 *
 * NOTE: This is a placeholder for truly shared types.
 * Most types remain in their respective backend/frontend directories.
 */
// Permissions types are defined in:
// - backend/src/config/permissions.ts (source of truth)
// - frontend/src/config/permissions.ts (generated from backend)
// 
// These are kept separate because:
// 1. Backend is the source of truth
// 2. Frontend version is generated by script
// 3. They may have different export patterns
// Add shared types here as needed
// Example:
// export type { SharedType } from './sharedType';
