/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Check API health status
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description API is healthy */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example ok */
              status?: string;
              /** Format: date-time */
              timestamp?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User login
     * @description Authenticate user and receive access/refresh tokens
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest'];
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
        /** @description Invalid credentials */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User registration
     * @description Register a new user account (returns pending status for teachers/students)
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['RegisterRequest'];
        };
      };
      responses: {
        /** @description Registration successful */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
        /** @description User already exists */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh access token
     * @description Get new access token using refresh token
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            refreshToken: string;
          };
        };
      };
      responses: {
        /** @description Token refreshed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              accessToken?: string;
            };
          };
        };
        /** @description Invalid refresh token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User logout
     * @description Logout user and invalidate tokens
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logout successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/students': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List students
     * @description Get paginated list of students for the current tenant
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by class ID */
          classId?: string;
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Students for the current tenant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaginatedResponse'];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    put?: never;
    /** Create student */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['StudentInput'];
        };
      };
      responses: {
        /** @description Student created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/students/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get student */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Resource UUID */
          id: components['parameters']['Id'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Student */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update student */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Resource UUID */
          id: components['parameters']['Id'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['StudentInput'];
        };
      };
      responses: {
        /** @description Student updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Delete student */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Resource UUID */
          id: components['parameters']['Id'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/teachers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List teachers */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Teachers for tenant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create teacher */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['TeacherInput'];
        };
      };
      responses: {
        /** @description Teacher created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/teachers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update teacher */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Resource UUID */
          id: components['parameters']['Id'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['TeacherInput'];
        };
      };
      responses: {
        /** @description Teacher updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Delete teacher */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Resource UUID */
          id: components['parameters']['Id'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/configuration/branding': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get tenant branding configuration */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Branding config for current tenant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BrandingConfig'];
          };
        };
      };
    };
    /** Upsert tenant branding configuration */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['BrandingInput'];
        };
      };
      responses: {
        /** @description Branding updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/configuration/terms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List academic terms */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Academic terms for tenant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AcademicTerm'][];
          };
        };
      };
    };
    put?: never;
    /** Create or update academic term */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AcademicTermInput'];
        };
      };
      responses: {
        /** @description Academic term created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/configuration/classes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List classes */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Classes for tenant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ClassRecord'][];
          };
        };
      };
    };
    put?: never;
    /** Create or update class */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ClassInput'];
        };
      };
      responses: {
        /** @description Class created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/school': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get school profile */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description School record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Upsert school profile */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['SchoolInput'];
        };
      };
      responses: {
        /** @description School updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/attendance/mark': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bulk mark attendance */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            records?: components['schemas']['AttendanceMark'][];
          };
        };
      };
      responses: {
        /** @description Attendance recorded */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/attendance/{studentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get student attendance history */
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
        };
        header?: never;
        path: {
          /** @description Resource UUID */
          id: components['parameters']['Id'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Attendance history */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/attendance/report/class': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Class attendance report for date */
    get: {
      parameters: {
        query: {
          class_id: string;
          date: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Report per status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports/attendance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Aggregate attendance between dates */
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          class_id?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Aggregated attendance rows */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AttendanceAggregate'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports/grades': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Grade distribution for exam */
    get: {
      parameters: {
        query: {
          exam_id: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Grade aggregate rows */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GradeAggregate'][];
          };
        };
        /** @description Missing exam id */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports/fees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Outstanding fee summary */
    get: {
      parameters: {
        query?: {
          status?: 'pending' | 'partial' | 'paid' | 'overdue' | 'refunded';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Fee aggregates */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FeeAggregate'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/exams': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an exam for the tenant */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ExamInput'];
        };
      };
      responses: {
        /** @description Exam created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/exams/{examId}/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create or update an exam session */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          examId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ExamSessionInput'];
        };
      };
      responses: {
        /** @description Session saved */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/grades/bulk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bulk grade entry */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['GradeBulkRequest'];
        };
      };
      responses: {
        /** @description Grades stored */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/results/{studentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get exam results for a student */
    get: {
      parameters: {
        query: {
          exam_id: string;
        };
        header?: never;
        path: {
          studentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Result payload */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ExamResult'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/results/{examId}/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export exam results */
    get: {
      parameters: {
        query?: {
          format?: 'csv' | 'pdf';
        };
        header?: never;
        path: {
          examId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Export streamed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invoices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create invoice for a student */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['InvoiceInput'];
        };
      };
      responses: {
        /** @description Invoice created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invoices/{studentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List invoices for student */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          studentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of invoices */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/payments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Payment webhook endpoint */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PaymentWebhook'];
        };
      };
      responses: {
        /** @description Webhook processed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users for current tenant */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Tenant users */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TenantUser'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update user role */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UserRoleUpdate'];
        };
      };
      responses: {
        /** @description Updated tenant user */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TenantUser'];
          };
        };
        /** @description User not found in tenant */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error?: {
        message?: string;
        code?: string;
        field?: string;
      };
    };
    PaginatedResponse: {
      data?: unknown[];
      pagination?: {
        page?: number;
        limit?: number;
        total?: number;
        totalPages?: number;
        hasNext?: boolean;
        hasPrev?: boolean;
      };
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
      /**
       * Format: uuid
       * @description Tenant UUID (optional if tenantName provided)
       */
      tenantId?: string;
      /** @description Tenant slug/name (optional if tenantId provided) */
      tenantName?: string;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
      /** @enum {string} */
      role: 'student' | 'teacher' | 'admin';
      /** Format: uuid */
      tenantId: string;
      tenantName?: string;
      /** @description Role-specific profile data */
      profile?: Record<string, never>;
    };
    AuthResponse: {
      /** @description JWT access token (15min expiry) */
      accessToken?: string;
      /** @description JWT refresh token (7 days expiry) */
      refreshToken?: string;
      user?: {
        /** Format: uuid */
        id?: string;
        /** Format: email */
        email?: string;
        /** @enum {string} */
        role?: 'student' | 'teacher' | 'hod' | 'admin' | 'superadmin';
        /** @enum {string} */
        status?: 'pending' | 'active' | 'suspended' | 'rejected';
        /** Format: uuid */
        tenantId?: string;
      };
    };
    StudentInput: {
      firstName: string;
      lastName: string;
      /** Format: date */
      dateOfBirth?: string;
      classId?: string;
      admissionNumber?: string;
      parentContacts?: {
        name?: string;
        relationship?: string;
        phone?: string;
      }[];
    };
    TeacherInput: {
      name: string;
      /** Format: email */
      email: string;
      subjects?: string[];
      assignedClasses?: string[];
    };
    BrandingInput: {
      logoUrl?: string;
      primaryColor?: string;
      secondaryColor?: string;
      themeFlags?: {
        [key: string]: boolean;
      };
      typography?: {
        [key: string]: unknown;
      };
      navigation?: {
        [key: string]: unknown;
      };
    };
    SchoolInput: {
      name: string;
      address?: {
        [key: string]: unknown;
      };
    };
    BrandingConfig: {
      /** Format: uri */
      logo_url?: string;
      primary_color?: string;
      secondary_color?: string;
      theme_flags?: {
        [key: string]: boolean;
      };
      typography?: {
        [key: string]: unknown;
      };
      navigation?: {
        [key: string]: unknown;
      };
    };
    AcademicTermInput: {
      name: string;
      /** Format: date */
      startsOn: string;
      /** Format: date */
      endsOn: string;
    };
    AcademicTerm: {
      id?: string;
      name?: string;
      /** Format: date */
      starts_on?: string;
      /** Format: date */
      ends_on?: string;
    };
    ClassInput: {
      name: string;
      description?: string;
    };
    ClassRecord: {
      id?: string;
      name?: string;
      description?: string;
    };
    AttendanceMark: {
      studentId: string;
      classId?: string;
      /** @enum {string} */
      status: 'present' | 'absent' | 'late';
      markedBy: string;
      /** Format: date */
      date: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    ExamInput: {
      name: string;
      description?: string;
      /** Format: date */
      examDate?: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    ExamSessionInput: {
      classId: string;
      subject: string;
      /** Format: date-time */
      scheduledAt: string;
      invigilator?: string;
    };
    GradeEntry: {
      studentId: string;
      subject: string;
      score: number;
      remarks?: string;
      classId?: string;
    };
    GradeBulkRequest: {
      examId: string;
      entries: components['schemas']['GradeEntry'][];
    };
    ExamResult: {
      exam?: {
        [key: string]: unknown;
      };
      summary?: {
        studentId?: string;
        total?: number;
        average?: number;
        percentage?: number;
        grade?: string;
        position?: number;
      };
      subjects?: {
        subject?: string;
        score?: number;
        grade?: string;
        remarks?: string;
      }[];
      aggregates?: {
        highest?: number;
        lowest?: number;
        classAverage?: number;
      };
      leaderboard?: {
        studentId?: string;
        total?: number;
        average?: number;
        grade?: string;
        position?: number;
      }[];
    };
    InvoiceInput: {
      studentId: string;
      /** Format: date-time */
      dueDate?: string;
      currency?: string;
      metadata?: {
        [key: string]: unknown;
      };
      items: {
        description: string;
        amount: number;
        metadata?: {
          [key: string]: unknown;
        };
      }[];
    };
    PaymentWebhook: {
      provider: string;
      type?: string;
      paymentId: string;
      invoiceId: string;
      amount?: number;
      currency?: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    AttendanceAggregate: {
      /** Format: date */
      attendance_date?: string;
      class_id?: string | null;
      status?: string;
      count?: number;
    };
    GradeAggregate: {
      subject?: string;
      grade?: string;
      count?: number;
      /** Format: float */
      average_score?: number;
    };
    FeeAggregate: {
      status?: string;
      invoice_count?: number;
      /** Format: float */
      total_amount?: number;
      /** Format: float */
      total_paid?: number;
    };
    TenantUser: {
      id?: string;
      /** Format: email */
      email?: string;
      /** @enum {string} */
      role?: 'student' | 'teacher' | 'admin' | 'superadmin';
      is_verified?: boolean;
      /** Format: date-time */
      created_at?: string;
    };
    UserRoleUpdate: {
      /** @enum {string} */
      role: 'student' | 'teacher' | 'admin' | 'superadmin';
    };
  };
  responses: {
    /** @description Authentication required */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Insufficient permissions */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Validation error */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    /** @description Resource UUID */
    Id: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
